config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "data#home"
  get 'updatematches', to: 'data#updatematches'
  get 'addchamps', to: 'champions#addchamps'
  get 'addchampionstomatches', to: 'champions#addchampionstomatches'

  resources :champions, only: [:show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion.rb
class Champion < ApplicationRecord
  validates :name, presence: true
  validates :champ_id, presence: true
  has_many :match_champions
  has_many :matches, through: :match_champions

  def win_rate
    if matches.count == 0
      return 0
    else
      wins = matches.where(win: true).count
      total = matches.count
      ((wins.to_f)/(total.to_f)).round(2)
    end
  end

  def self.sort_by_win_rate
    champions = Champion.joins(:matches).group('champions.id').having('COUNT(champions.*) >=1')
    champions.sort_by {|c| c.win_rate}.reverse
  end


end

app/models/match.rb
class Match < ApplicationRecord
  validates_uniqueness_of :game_id
  has_many :match_champions
  has_many :champions, through: :match_champions
end

app/models/match_champion.rb
class MatchChampion < ApplicationRecord
  belongs_to :match
  belongs_to :champion

end

app/models/player.rb
class Player < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController

  def index
    @filter = params[:filter]
    if @filter == "matches1"
      @champions = Champion.joins(:matches).group('champions.id').having('COUNT(champions.*) >=1').order(:name)
    elsif @filter == "matches5"
      @champions = Champion.joins(:matches).group('champions.id').having('COUNT(champions.*) >=5').order(:name)
    elsif @filter == "matches10"
      @champions = Champion.joins(:matches).group('champions.id').having('COUNT(champions.*) >=10').order(:name)
    elsif @filter == "win-rate"
      @champions = Champion.sort_by_win_rate
    elsif @filter == "all"
      @champions = Champion.all
    else
      @champions = Champion.all
    end
  end

  def show
    @champion = Champion.find(params[:id])
    @win_rate = @champion.win_rate
  end


  def addchamps
    champion_service = ChampionService.new
    champion_service.add_champs
    redirect_to root_path
  end

  def addchampionstomatches
    champion_service = RiotService.new('RGAPI-564e5c01-d390-4103-9279-79977fcc27ae')
    champion_service.add_champions_to_matches
    redirect_to root_path
  end


end

app/controllers/data_controller.rb
class DataController < ApplicationController

  def home
    match_data = Match.all
    @count = match_data.count
    @matches = match_data.order(start_time: :desc)
    @wins = match_data.where(win: true).count
    @losses = match_data.where(win: false).count
    @win_percent = ((@wins.to_f)/(@matches.count.to_f)*100).round(2)
  end

  def updatematches
    riot_service = RiotService.new('RGAPI-bd04065e-6637-4836-a160-98d2a4ef41b6')
    riot_service.update_matches
    riot_service.add_champions_to_matches
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_date(time)
    new_time = time.to_s[0..-4].to_i
    zone = ActiveSupport::TimeZone.new("Central Time (US & Canada)")
    Time.at(new_time).in_time_zone(zone)
  end
end

app/views/champions/index.html.erb
<form>
    <h3 class="sort-label">Filter: </h3>
    <select id="filter-champions" onchange="location = this.value;">
      <option
        value="champions"
        <%= "selected='selected'" unless @filter %>>
        Select
      </option>
      <option value="champions"
        <%= "selected='selected'" if @filter == "all" %>>
        All Champions
      </option>
      <option value="champions?filter=matches1"
        <%= "selected='selected'" if @filter == "more-than-1" %>>
        At least 1 game
      </option>
      <option value="champions?filter=matches5"
        <%= "selected='selected'" if @filter == "more-than-5" %>>
        At least 5 game
      </option>
      <option value="champions?filter=matches10"
        <%= "selected='selected'" if @filter == "more-than-10" %>>
        At least 10 game
      </option>
      <option value="champions?filter=win-rate"
        <%= "selected='selected'" if @filter == "win-rate" %>>
        Win Rate
      </option>
    </select>
  </form>


<ul>
  <% @champions.each do |c| %>
    <li>
      <%=link_to c.name, champion_path(c) %> Win Rate: <%=c.win_rate%> Total Games: <%= c.matches.count%>
    </li>
  <% end %>
</ul>

app/views/champions/show.html.erb
<h1> <%=@champion.name %> </h1>
<p>Win Rate: <%=@win_rate%> %</p>

app/views/data/home.html.erb
<p>Total Matches: <%=@count%></p>
<p>Total Wins: <%=@wins%></p>
<p>Total Losses: <%=@losses%></p>
<p>Win Rate: <%=@win_percent%>%</p>

<ul>
  <% @matches.each do |m| %>
    <li>
      <%=m.win%> Date: <%= get_date(m.start_time)%>
        <ul>
          <%m.champions.each do |c|%>
            <li><%=c.name %></li>
          <%end%>
        </ul>
    </li>
  <% end %>
</ul>

app/views/layouts/_navigation.html.erb
<div>
  <p><%= link_to "Champions", champions_path%> <%=link_to "Matches", root_path%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuadTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>